# Generated by Django 3.0.1 on 2020-01-08 06:57

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=80)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=10, unique=True)),
                ('subcategory_image', models.ImageField(blank=True, null=True, unique=True, upload_to='')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=60)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(unique=True, upload_to=product.models.upload_productimage)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True)),
                ('active', models.BooleanField(default=True)),
                ('price', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
                ('subcategory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SubCategory')),
            ],
        ),
    ]
