# Generated by Django 3.0.1 on 2020-01-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200111_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='productid',
            field=models.IntegerField(),
        ),
    ]
